### ISSUE TITLE
Create resources endpoints

### ISSUE THREAD

**Issue by jenny-alexander** [chingu-x/chingu-dashboard-be#18]
Requirements can be found here: https://suwanna.atlassian.net/wiki/spaces/SD/pages/13828097/Features+Page

**Comment by jenny-alexander** [comment]
Requirements can be found here: https://suwanna.atlassian.net/wiki/spaces/SD/pages/13828097/Features+Page

**Comment by jenny-alexander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CGD-18 Create Resources endpoints](https://trello.com/c/yjiIglUr/22-cgd-18-create-resources-endpoints)

**Comment by cherylli** [comment]
closing as PR merged
