### ISSUE TITLE
Implement API endpoint for onboarding tasks

### ISSUE THREAD

**Issue by jenny-alexander** [chingu-x/chingu-dashboard-be#55]
This would involve onboarding tasks/checklists related to:

- joining Discord
- solo project submission
- joining Chingu voyage submission

**Comment by jenny-alexander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CGD-55: Implement API endpoint for onboarding checklists](https://trello.com/c/b1pAA8gs/67-cgd-55-implement-api-endpoint-for-onboarding-checklists)

**Comment by cherylli** [comment]
I think this one can be combined with all the onboarding checklists

**Comment by jenny-alexander** [comment]
> I think this one can be combined with all the onboarding checklists

I updated the task to reflect this.

**Comment by jenny-alexander** [comment]
Not needed for 1st release of Chingu Platform.
