### ISSUE TITLE
Add tables and seed data for Onboarding checklist

### ISSUE THREAD

**Issue by jenny-alexander** [chingu-x/chingu-dashboard-be#68]
See Trello card for details.

**Comment by jenny-alexander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CGD-68: Add tables and seed data for Onboarding checklist](https://trello.com/c/gpuJI5CF/76-cgd-68-add-tables-and-seed-data-for-onboarding-checklist)

**Comment by cherylli** [comment]
completed #63
