### ISSUE TITLE
Implement Authentication (guards) to limit access to routes

### ISSUE THREAD

**Issue by jenny-alexander** [chingu-x/chingu-dashboard-be#75]
https://docs.nestjs.com/guards

**Comment by jenny-alexander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add custom guards (role-based, permission-based)](https://trello.com/c/NkYtX8hz/87-add-custom-guards-role-based-permission-based)

**Comment by cherylli** [comment]
#97
